/**
 * scripts/onboard-tenant.js
 *
 * Run after creating a new client via the admin dashboard.
 * Does three things:
 *   1. Creates .env.<slug> with minimal container config
 *   2. Appends a new service block to docker-compose.yml
 *   3. Prints the docker-compose up command to start the container
 *
 * Usage:
 *   node scripts/onboard-tenant.js --tenant-id=<uuid> --slug=<short-name> --host-port=<port>
 *
 * Example:
 *   node scripts/onboard-tenant.js --tenant-id=4d8eae78-... --slug=clinic-demo --host-port=3002
 */

import 'dotenv/config';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import pg from 'pg';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT      = join(__dirname, '..');

// ── Parse CLI args ────────────────────────────────────────────────────────────

function arg(name) {
  const flag = process.argv.find(a => a.startsWith(`--${name}=`));
  return flag ? flag.split('=').slice(1).join('=') : null;
}

const tenantId = arg('tenant-id');
const slug     = arg('slug');
const hostPort = arg('host-port');

if (!tenantId || !slug || !hostPort) {
  console.error('Usage: node scripts/onboard-tenant.js --tenant-id=<uuid> --slug=<short-name> --host-port=<port>');
  process.exit(1);
}

const envFilePath     = join(ROOT, `.env.${slug}`);
const dockerComposePath = join(ROOT, 'docker-compose.yml');

// ── Verify client exists in DB ────────────────────────────────────────────────

const dbClient = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: false } : false,
});

await dbClient.connect();

const { rows } = await dbClient.query(
  'SELECT id, name, email, whatsapp_business_id FROM clients WHERE id = $1',
  [tenantId]
);

if (rows.length === 0) {
  console.error(`No client found with id=${tenantId}`);
  console.error('Create the client via the admin dashboard first.');
  await dbClient.end();
  process.exit(1);
}

const tenant = rows[0];
console.log(`\nOnboarding: ${tenant.name} (${tenant.email})`);
console.log(`  TENANT_ID:          ${tenant.id}`);
console.log(`  whatsapp_phone_id:  ${tenant.whatsapp_business_id || '(not set — add via admin dashboard)'}`);

await dbClient.end();

// ── 1. Generate env file ──────────────────────────────────────────────────────

if (existsSync(envFilePath)) {
  console.warn(`\n[warn] ${envFilePath} already exists — skipping env file creation`);
} else {
  const envContent = `# Auto-generated by scripts/onboard-tenant.js
# Tenant: ${tenant.name} (${tenant.email})

TENANT_ID=${tenant.id}

DATABASE_URL=${process.env.DATABASE_URL}
DATABASE_SSL=${process.env.DATABASE_SSL || 'true'}

REDIS_HOST=${process.env.REDIS_HOST || 'redis'}
REDIS_PORT=${process.env.REDIS_PORT || '6379'}
REDIS_PREFIX=${slug}

ENCRYPTION_KEY=${process.env.ENCRYPTION_KEY}
JWT_SECRET=${process.env.JWT_SECRET}

NODE_ENV=production
PORT=3000
USE_RAG=${process.env.USE_RAG || 'true'}

# Fallback AI keys (used if not stored on the client record in DB)
GEMINI_API_KEY=${process.env.GEMINI_API_KEY || ''}
PINECONE_API_KEY=${process.env.PINECONE_API_KEY || ''}
PINECONE_INDEX_NAME=${process.env.PINECONE_INDEX_NAME || ''}
PINECONE_NAMESPACE=${slug}

# WhatsApp credentials are read from the clients DB record (encrypted).
# Only needed here as a fallback if the DB record has no token yet.
WHATSAPP_WEBHOOK_VERIFY_TOKEN=${process.env.WHATSAPP_WEBHOOK_VERIFY_TOKEN || 'moyo_tech_secret_2025'}
`;

  writeFileSync(envFilePath, envContent);
  console.log(`\n[ok] Created ${envFilePath}`);
}

// ── 2. Append to docker-compose.yml ──────────────────────────────────────────

const composeContent = readFileSync(dockerComposePath, 'utf8');
const serviceBlock   = `
  yayah-${slug}:
    image: yayah:latest
    container_name: yayah-${slug}
    restart: always
    networks:
      - app_yaya-dev
    ports:
      - "127.0.0.1:${hostPort}:3000"
    env_file:
      - .env.${slug}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: sh -c "node scripts/migrate.js && node app.js"
`;

if (composeContent.includes(`container_name: yayah-${slug}`)) {
  console.warn(`[warn] Service yayah-${slug} already exists in docker-compose.yml — skipping`);
} else {
  writeFileSync(dockerComposePath, composeContent + serviceBlock);
  console.log(`[ok] Added service yayah-${slug} to docker-compose.yml (host port ${hostPort})`);
}

// ── 3. Print next steps ───────────────────────────────────────────────────────

console.log(`
───────────────────────────────────────────────────────
Next steps:

1. Start the container:
   docker compose up -d yayah-${slug}

2. Register the Meta webhook for phone ${tenant.whatsapp_business_id || '<phone-number-id>'}:
   The webhook URL on your server is:
   https://<your-domain>/ai/${slug}/webhook   (if using path-based routing)
   OR configure the phone number webhook override via Graph API.

3. Verify it's healthy:
   docker compose ps yayah-${slug}
   curl http://localhost:${hostPort}/health
───────────────────────────────────────────────────────
`);
